import nltk
from nltk.corpus import wordnet as wn


master_list = ['airplane', 'ambulance', 'angel', 'ant', 'anvil', 'apple', 'arm', 'asparagus', 'axe', 'backpack', 'banana', 'bandage', 'barn', 'baseball', 'basket', 'basketball', 'bat', 'bathtub', 'beach', 'bear', 'beard', 'bed', 'bee', 'belt', 'bench', 'bicycle', 'binoculars', 'bird', 'blackberry', 'blueberry', 'book', 'boomerang', 'bowtie', 'bracelet', 'brain', 'bread', 'bridge', 'broccoli', 'broom', 'bucket', 'bulldozer', 'bus', 'bush', 'butterfly', 'cactus', 'cake', 'calculator', 'calendar', 'camel', 'camera', 'camouflage', 'campfire', 'candle', 'cannon', 'canoe', 'car', 'carrot', 'castle', 'cat', 'cello', 'chair', 'chandelier', 'church', 'circle', 'clarinet', 'clock', 'cloud', 'compass', 'computer', 'cookie', 'cooler', 'couch', 'cow', 'crab', 'crayon', 'crocodile', 'crown', 'cup', 'diamond', 'dishwasher', 'dog', 'dolphin', 'door', 'dragon', 'dresser', 'drill', 'duck', 'dumbbell', 'ear', 'elbow', 'elephant', 'envelope', 'eraser', 'eye', 'eyeglasses', 'face', 'fan', 'feather', 'fence', 'finger', 'fireplace', 'firetruck', 'fish', 'flamingo', 'flashlight', 'flower', 'foot', 'fork', 'frog', 'garden', 'giraffe', 'goatee', 'grass', 'guitar', 'hamburger', 'hammer', 'hand', 'harp', 'hat', 'headphones', 'hedgehog', 'helicopter', 'helmet', 'hexagon', 'horse', 'hospital', 'hourglass', 'house', 'hurricane', 'jacket', 'jail', 'kangaroo', 'key', 'keyboard', 'knee', 'knife', 'ladder', 'lantern', 'laptop', 'leaf', 'leg', 'lighter', 'lighthouse', 'lightning', 'line', 'lion', 'lipstick', 'lobster', 'lollipop', 'mailbox', 'map', 'marker', 'megaphone', 'mermaid', 'microphone', 'microwave', 'monkey', 'moon', 'mosquito', 'motorbike', 'mountain', 'mouse', 'moustache', 'mouth', 'mug', 'mushroom', 'nail', 'necklace', 'nose', 'ocean', 'octagon', 'octopus', 'onion', 'oven', 'owl', 'paintbrush', 'panda', 'pants', 'parachute', 'parrot', 'passport', 'peanut', 'pear', 'pencil', 'penguin', 'piano', 'pig', 'pillow', 'pineapple', 'pizza', 'pliers', 'pond', 'pool', 'popsicle', 'postcard', 'potato', 'purse', 'rabbit', 'raccoon', 'radio', 'rain', 'rainbow', 'rake', 'rhinoceros', 'rifle', 'river', 'sailboat', 'sandwich', 'saw', 'saxophone', 'scissors', 'scorpion', 'screwdriver', 'shark', 'sheep', 'shoe', 'shorts', 'shovel', 'sink', 'skateboard', 'skull', 'skyscraper', 'snail', 'snake', 'snorkel', 'snowflake', 'snowman', 'sock', 'speedboat', 'spider', 'spoon', 'spreadsheet', 'square', 'squiggle', 'squirrel', 'stairs', 'star', 'steak', 'stereo', 'stethoscope', 'stove', 'strawberry', 'streetlight', 'submarine', 'suitcase', 'sun', 'swan', 'sweater', 'swing', 'sword', 'syringe', 'table', 'teapot', 'telephone', 'television', 'tent', 'tiger', 'toaster', 'toe', 'toilet', 'tooth', 'toothbrush', 'toothpaste', 'tornado', 'tractor', 'train', 'tree', 'triangle', 'trombone', 'truck', 'trumpet', 'umbrella', 'underwear', 'van', 'vase', 'violin', 'watermelon', 'whale', 'wheel', 'windmill', 'wristwatch', 'yoga', 'zebra', 'zigzag']


def get_synset(a_list):
    synset_list = []
    for word in a_list:
        a = wn.synsets(word)[:1] 
        synset_list.append(a)
    return synset_list
master_synsets = get_synset(master_list)


def wn_syns(given_list): 
       synset_wn = []
       for word in given_list:
           synset_wn.append("wn.[%s]" % word)
       return synset_wn
master_wn = wn_syns(master_synsets)


def lower(list):
    new_list = []
    for word in list:
        new_list.append(word.lower())
    return new_list
lower_m = lower(master_wn)


def clean(a_list): 
    new_list = []
    for word in a_list:
        w = word.replace("[", "").replace("]", "").replace("wn.synset", "").replace("(", "").replace(")", "").replace("'", "")
        new_list.append(w)
    return new_list
clean_m = clean(lower_m)


# # # Get Definitions # # #
## word = wn.synset('word.n.01').definition() ##

airplane = wn.synset('airplane.n.01').definition()
print(airplane)
ambulance = wn.synset('ambulance.n.01').definition()
print(ambulance)
angel = wn.synset('angel.n.01').definition()
print(angel)
ant = wn.synset('ant.n.01').definition()
print(ant)
anvil = wn.synset('anvil.n.01').definition()
print(anvil)
apple = wn.synset('apple.n.01').definition()
print(apple)
arm = wn.synset('arm.n.01').definition()
print(arm)
asparagus = wn.synset('asparagus.n.01').definition()
print(asparagus)
axe = wn.synset('ax.n.01').definition()
print(axe)
backpack = wn.synset('backpack.n.01').definition()
print(backpack)
banana = wn.synset('banana.n.01').definition()
print(banana)
bandage = wn.synset('bandage.n.01').definition()
print(bandage)
barn = wn.synset('barn.n.01').definition()
print(barn)
baseball = wn.synset('baseball.n.01').definition()
print(baseball)
basket = wn.synset('basket.n.01').definition()
print(basket)
basketball = wn.synset('basketball.n.01').definition()
print(basketball)
bat = wn.synset('bat.n.01').definition()
print(bat)
bathtub = wn.synset('bathtub.n.01').definition()
print(bathtub)
beach = wn.synset('beach.n.01').definition()
print(beach)
bear = wn.synset('bear.n.01').definition()
print(bear)
beard = wn.synset('beard.n.01').definition()
print(beard)
bed = wn.synset('bed.n.01').definition()
print(bed)
bee = wn.synset('bee.n.01').definition()
print(bee)
belt = wn.synset('belt.n.01').definition()
print(belt)
bench = wn.synset('bench.n.01').definition()
print(bench)
bicycle = wn.synset('bicycle.n.01').definition()
print(bicycle)
binoculars = wn.synset('binoculars.n.01').definition()
print(binoculars)
bird = wn.synset('bird.n.01').definition()
print(bird)
blackberry = wn.synset('blackberry.n.01').definition()
print(blackberry)
blueberry = wn.synset('blueberry.n.01').definition()
print(blueberry)
book = wn.synset('book.n.01').definition()
print(book)
boomerang = wn.synset('boomerang.n.01').definition()
print(boomerang)
bowtie = wn.synset('bow_tie.n.01').definition()
print(bowtie)
bracelet = wn.synset('watchband.n.01').definition()
print(bracelet)
brain = wn.synset('brain.n.01').definition()
print(brain)
bread = wn.synset('bread.n.01').definition()
print(bread)
bridge = wn.synset('bridge.n.01').definition()
print(bridge)
broccoli = wn.synset('broccoli.n.01').definition()
print(broccoli)
broom = wn.synset('broom.n.01').definition()
print(broom)
bucket = wn.synset('bucket.n.01').definition()
print(bucket)
bulldozer = wn.synset('bulldozer.n.01').definition()
print(bulldozer)
bus = wn.synset('bus.n.01').definition()
print(bus)
bush = wn.synset('shrub.n.01').definition()
print(bush)
butterfly = wn.synset('butterfly.n.01').definition()
print(butterfly)
cactus = wn.synset('cactus.n.01').definition()
print(cactus)
cake = wn.synset('cake.n.01').definition()
print(cake)
calculator = wn.synset('calculator.n.01').definition()
print(calculator)
calendar = wn.synset('calendar.n.01').definition()
print(calendar)
camel = wn.synset('camel.n.01').definition()
print(camel)
camera = wn.synset('camera.n.01').definition()
print(camera)
camouflage = wn.synset('disguise.n.01').definition()
print(camouflage)
campfire = wn.synset('campfire.n.01').definition()
print(campfire)
candle = wn.synset('candle.n.01').definition()
print(candle)
cannon = wn.synset('cannon.n.01').definition()
print(cannon)
canoe = wn.synset('canoe.n.01').definition()
print(canoe)
car = wn.synset('car.n.01').definition()
print(car)
carrot = wn.synset('carrot.n.01').definition()
print(carrot)
castle = wn.synset('palace.n.01').definition()
print(castle)
cat = wn.synset('cat.n.01').definition()
print(cat)
cello = wn.synset('cello.n.01').definition()
print(cello)
chair = wn.synset('chair.n.01').definition()
print(chair)
chandelier = wn.synset('chandelier.n.01').definition()
print(chandelier)
church = wn.synset('church.n.01').definition()
print(church)
circle = wn.synset('circle.n.01').definition()
print(circle)
clarinet = wn.synset('clarinet.n.01').definition()
print(clarinet)
clock = wn.synset('clock.n.01').definition()
print(clock)
cloud = wn.synset('cloud.n.01').definition()
print(cloud)
compass = wn.synset('compass.n.01').definition()
print(compass)
computer = wn.synset('computer.n.01').definition() 
print(computer)
cookie = wn.synset('cookie.n.01').definition()
print(cookie)
cooler = wn.synset('cooler.n.01').definition()
print(cooler)
couch = wn.synset('sofa.n.01').definition()
print(couch)
cow = wn.synset('cow.n.01').definition()
print(cow)
crab = wn.synset('crab.n.01').definition()
print(crab)
crayon = wn.synset('crayon.n.01').definition()
print(crayon)
crocodile = wn.synset('crocodile.n.01').definition()
print(crocodile)
crown = wn.synset('crown.n.01').definition()
print(crown)
cup = wn.synset('cup.n.01').definition()
print(cup)
diamond = wn.synset('diamond.n.01').definition()
print(diamond)
dishwasher = wn.synset('dishwasher.n.01').definition()
print(dishwasher)
dog = wn.synset('dog.n.01').definition()
print(dog)
dolphin = wn.synset('dolphinfish.n.02').definition()
print(dolphin)
door = wn.synset('door.n.01').definition()
print(door)
dragon = wn.synset('dragon.n.01').definition()
print(dragon)
dresser = wn.synset('chest_of_drawers.n.01').definition()
print(dresser)
drill = wn.synset('drill.n.01').definition()
print(drill)
duck = wn.synset('duck.n.01').definition()
print(duck)
dumbbell = wn.synset('dumbbell.n.01').definition()
print(dumbbell)
ear = wn.synset('ear.n.01').definition()
print(ear)
elbow = wn.synset('elbow.n.01').definition()
print(elbow)
elephant = wn.synset('elephant.n.01').definition()
print(elephant)
envelope = wn.synset('envelope.n.01').definition()
print(envelope)
eraser = wn.synset('eraser.n.01').definition()
print(eraser)
eye = wn.synset('eye.n.01').definition()
print(eye)
eyeglasses = wn.synset('spectacles.n.01').definition()
print(eyeglasses)
face = wn.synset('face.n.01').definition()
print(face)
fan = wn.synset('fan.n.01').definition()
print(fan)
feather = wn.synset('feather.n.01').definition()
print(feather)
fence = wn.synset('fence.n.01').definition()
print(fence)
finger = wn.synset('finger.n.01').definition()
print(finger)
fireplace = wn.synset('fireplace.n.01').definition()
print(fireplace)
# firetruck = wn.synset('wn.').definition()
fish = wn.synset('fish.n.01').definition()
print(fish)
flamingo = wn.synset('flamingo.n.01').definition()
print(flamingo)
flashlight = wn.synset('flashlight.n.01').definition()
print(flashlight)
flower = wn.synset('flower.n.01').definition()
print(flower)
foot = wn.synset('foot.n.01').definition()
print(foot)
fork = wn.synset('fork.n.01').definition()
print(fork)
frog = wn.synset('frog.n.01').definition()
print(frog)
garden = wn.synset('garden.n.01').definition()
print(garden)
giraffe = wn.synset('giraffe.n.01').definition()
print(giraffe)
goatee = wn.synset('goatee.n.01').definition()
print(goatee)
grass = wn.synset('grass.n.01').definition()
print(grass)
guitar = wn.synset('guitar.n.01').definition()
print(guitar)
hamburger = wn.synset('hamburger.n.01').definition()
print(hamburger)
hammer = wn.synset('hammer.n.01').definition()
print(hammer)
hand = wn.synset('hand.n.01').definition()
print(hand)
harp = wn.synset('harp.n.01').definition()
print(harp)
hat = wn.synset('hat.n.01').definition()
print(hat)
headphones = wn.synset('earphone.n.01').definition()
print(headphones)
hedgehog = wn.synset('porcupine.n.01').definition()
print(hedgehog)
helicopter = wn.synset('helicopter.n.01').definition()
print(helicopter)
helmet = wn.synset('helmet.n.01').definition()
print(helmet)
hexagon = wn.synset('hexagon.n.01').definition()
print(hexagon)
horse = wn.synset('horse.n.01').definition()
print(horse)
hospital = wn.synset('hospital.n.01').definition()
print(hospital)
hourglass = wn.synset('hourglass.n.01').definition()
print(hourglass)
house = wn.synset('house.n.01').definition()
print(house)
hurricane = wn.synset('hurricane.n.01').definition()
print(hurricane)
jacket = wn.synset('jacket.n.01').definition()
print(jacket)
jail = wn.synset('jail.n.01').definition()
print(jail)
kangaroo = wn.synset('kangaroo.n.01').definition()
print(kangaroo)
key = wn.synset('key.n.01').definition()
print(key)
keyboard = wn.synset('keyboard.n.01').definition()
print(keyboard)
knee = wn.synset('knee.n.01').definition()
print(knee)
knife = wn.synset('knife.n.01').definition()
print(knife)
ladder = wn.synset('ladder.n.01').definition()
print(ladder)
lantern = wn.synset('lantern.n.01').definition()
print(lantern)
laptop = wn.synset('laptop.n.01').definition()
print(laptop)
leaf = wn.synset('leaf.n.01').definition()
print(leaf)
leg = wn.synset('leg.n.01').definition()
print(leg)
lighter = wn.synset('igniter.n.01').definition()
print(lighter)
lighthouse = wn.synset('beacon.n.03').definition()
print(lighthouse)
lightning = wn.synset('lightning.n.01').definition()
print(lightning)
line = wn.synset('line.n.01').definition()
print(line)
lion = wn.synset('lion.n.01').definition()
print(lion)
lipstick = wn.synset('lipstick.n.01').definition()
print(lipstick)
lobster = wn.synset('lobster.n.01').definition()
print(lobster)
lollipop = wn.synset('ice_lolly.n.01').definition()
print(lollipop)
mailbox = wn.synset('mailbox.n.01').definition()
print(mailbox)
map_ = wn.synset('map.n.01').definition()
print(map_)
marker = wn.synset('marker.n.01').definition() 
print(marker)
megaphone = wn.synset('megaphone.n.01').definition()
print(megaphone)
mermaid = wn.synset('mermaid.n.01').definition() 
print(mermaid)
microphone = wn.synset('microphone.n.01').definition()
print(microphone)
microwave = wn.synset('microwave.n.01').definition()
print(microwave)
monkey = wn.synset('monkey.n.01').definition()
print(monkey)
moon = wn.synset('moon.n.01').definition()
print(moon)
mosquito = wn.synset('mosquito.n.01').definition()
print(mosquito)
motorbike = wn.synset('minibike.n.01').definition()
print(motorbike)
mountain = wn.synset('mountain.n.01').definition()
print(mountain)
mouse = wn.synset('mouse.n.01').definition()
print(mouse)
moustache = wn.synset('mustache.n.01').definition()
print(moustache)
mouth = wn.synset('mouth.n.01').definition()
print(mouth)
mug = wn.synset('mug.n.01').definition()
print(mug)
mushroom = wn.synset('mushroom.n.01').definition()
print(mushroom)
nail = wn.synset('nail.n.01').definition()
print(nail)
necklace = wn.synset('necklace.n.01').definition()
print(necklace)
nose = wn.synset('nose.n.01').definition()
print(nose)
ocean = wn.synset('ocean.n.01').definition()
print(ocean)
octagon = wn.synset('octagon.n.01').definition()
print(octagon)
octopus = wn.synset('octopus.n.01').definition()
print(octopus)
onion = wn.synset('onion.n.01').definition()
print(onion)
oven = wn.synset('oven.n.01').definition()
print(oven)
owl = wn.synset('owl.n.01').definition()
print(owl)
paintbrush = wn.synset('paintbrush.n.01').definition()
print(paintbrush)
panda = wn.synset('giant_panda.n.01').definition()
print(panda)
pants = wn.synset('bloomers.n.01').definition()
print(pants)
parachute = wn.synset('parachute.n.01').definition()
print(parachute)
parrot = wn.synset('parrot.n.01').definition()
print(parrot)
passport = wn.synset('pass.n.05').definition()
print(passport)
peanut = wn.synset('peanut.n.01').definition()
print(peanut)
pear = wn.synset('pear.n.01').definition()
print(pear)
pencil = wn.synset('pencil.n.01').definition()
print(pencil)
penguin = wn.synset('penguin.n.01').definition()
print(penguin)
piano = wn.synset('piano.n.01').definition() 
print(piano)
pig = wn.synset('hog.n.03').definition()
print(pig)
pillow = wn.synset('pillow.n.01').definition() 
print(pillow)
pineapple = wn.synset('pineapple.n.01').definition()
print(pineapple)
pizza = wn.synset('pizza.n.01').definition()
print(pizza)
pliers = wn.synset('pliers.n.01').definition()
print(pliers)
pond = wn.synset('pond.n.01').definition()
print(pond)
pool = wn.synset('pool.n.01').definition()
print(pool)
popsicle = wn.synset('ice_lolly.n.01').definition()
print(popsicle)
postcard = wn.synset('postcard.n.01').definition()
print(postcard)
potato = wn.synset('potato.n.01').definition()
print(potato)
purse = wn.synset('bag.n.04').definition()
print(purse)
rabbit = wn.synset('rabbit.n.01').definition()
print(rabbit)
raccoon = wn.synset('raccoon.n.01').definition()
print(raccoon)
radio = wn.synset('radio.n.01').definition()
print(radio)
rain = wn.synset('rain.n.01').definition()
print(rain)
rainbow = wn.synset('rainbow.n.01').definition()
print(rainbow)
rake = wn.synset('rake.n.01').definition()
print(rake)
rhinoceros = wn.synset('rhinoceros.n.01').definition()
print(rhinoceros)
rifle = wn.synset('rifle.n.01').definition()
print(rifle)
river = wn.synset('river.n.01').definition()
print(river)
sailboat = wn.synset('sailboat.n.01').definition()
print(sailboat)
sandwich = wn.synset('sandwich.n.01').definition()
print(sandwich)
saw = wn.synset('proverb.n.01').definition()
print(saw)
saxophone = wn.synset('sax.n.02').definition()
print(saxophone)
scissors = wn.synset('scissors.n.01').definition()
print(scissors)
scorpion = wn.synset('scorpio.n.01').definition()
print(scorpion)
screwdriver = wn.synset('screwdriver.n.01').definition()
print(screwdriver)
shark = wn.synset('shark.n.01').definition()
print(shark)
sheep = wn.synset('sheep.n.01').definition()
print(sheep)
shoe = wn.synset('shoe.n.01').definition()
print(shoe)
shorts = wn.synset('short_pants.n.01').definition()
print(shorts)
shovel = wn.synset('shovel.n.01').definition()
print(shovel)
sink = wn.synset('sink.n.01').definition()
print(sink)
skateboard = wn.synset('skateboard.n.01').definition() 
print(skateboard)
skull = wn.synset('skull.n.01').definition()
print(skull)
skyscraper = wn.synset('skyscraper.n.01').definition()
print(skyscraper)
snail = wn.synset('snail.n.01').definition()
print(snail)
snake = wn.synset('snake.n.01').definition()
print(snake)
snorkel = wn.synset('snorkel.n.01').definition()
print(snorkel)
snowflake = wn.synset('snowflake.n.01').definition()
print(snowflake)
snowman = wn.synset('snowman.n.01').definition()
print(snowman)
sock = wn.synset('sock.n.01').definition()
print(sock)
speedboat = wn.synset('speedboat.n.01').definition()
print(speedboat)
spider = wn.synset('spider.n.01').definition()
print(spider)
spoon = wn.synset('spoon.n.01').definition()
print(spoon)
spreadsheet = wn.synset('spreadsheet.n.01').definition()
print(spreadsheet)
square = wn.synset('square.n.01').definition()
print(square)
squiggle = wn.synset('squiggle.n.01').definition()
print(squiggle)
squirrel = wn.synset('squirrel.n.01').definition()
print(squirrel)
stairs = wn.synset('stairs.n.01').definition()
print(stairs)
star = wn.synset('star.n.01').definition()
print(star)
steak = wn.synset('steak.n.01').definition()
print(steak)
stereo = wn.synset('stereo.n.01').definition()
print(stereo)
stethoscope = wn.synset('stethoscope.n.01').definition()
print(stethoscope)
stove = wn.synset('stove.n.01').definition()
print(stove)
strawberry = wn.synset('strawberry.n.01').definition()
print(strawberry)
streetlight = wn.synset('streetlight.n.01').definition()
print(streetlight)
submarine = wn.synset('submarine.n.01').definition()
print(submarine)
suitcase = wn.synset('bag.n.06').definition()
print(suitcase)
sun = wn.synset('sun.n.01').definition()
print(sun)
swan = wn.synset('swan.n.01').definition()
print(swan)
sweater = wn.synset('sweater.n.01').definition()
print(sweater)
swing = wn.synset('swing.n.01').definition()
print(swing)
sword = wn.synset('sword.n.01').definition()
print(sword)
syringe = wn.synset('syringe.n.01').definition()
print(syringe)
table = wn.synset('table.n.01').definition()
print(table)
teapot = wn.synset('teapot.n.01').definition()
print(teapot)
telephone = wn.synset('telephone.n.01').definition()
print(telephone)
television = wn.synset('television.n.01').definition()
print(television)
tent = wn.synset('tent.n.01').definition()
print(tent)
tiger = wn.synset('tiger.n.01').definition()
print(tiger)
toaster = wn.synset('toaster.n.01').definition()
print(toaster)
toe = wn.synset('toe.n.01').definition()
print(toe)
toilet = wn.synset('toilet.n.01').definition()
print(toilet)
tooth = wn.synset('tooth.n.01').definition()
print(tooth)
toothbrush = wn.synset('toothbrush.n.01').definition()
print(toothbrush)
toothpaste = wn.synset('toothpaste.n.01').definition()
print(toothpaste)
tornado = wn.synset('tornado.n.01').definition()
print(tornado)
tractor = wn.synset('tractor.n.01').definition()
print(tractor)
train = wn.synset('train.n.01').definition()
print(train)
tree = wn.synset('tree.n.01').definition()
print(tree)
triangle = wn.synset('triangle.n.01').definition()
print(triangle)
trombone = wn.synset('trombone.n.01').definition()
print(trombone)
truck = wn.synset('truck.n.01').definition()
print(truck)
trumpet = wn.synset('cornet.n.01').definition()
print(trumpet)
umbrella = wn.synset('umbrella.n.01').definition()
print(umbrella)
underwear = wn.synset('underwear.n.01').definition()
print(underwear)
van = wn.synset('avant-garde.n.01').definition()
print(van)
vase = wn.synset('vase.n.01').definition()
print(vase)
violin = wn.synset('violin.n.01').definition()
print(violin)
watermelon = wn.synset('watermelon.n.01').definition()
print(watermelon)
whale = wn.synset('giant.n.04').definition()
print(whale)
wheel = wn.synset('wheel.n.01').definition()
print(wheel)
windmill = wn.synset('windmill.n.01').definition()
print(windmill)
wristwatch = wn.synset('wristwatch.n.01').definition()
print(wristwatch)
yoga = wn.synset('yoga.n.01').definition()
print(yoga)
zebra = wn.synset('zebra.n.01').definition()
print(zebra)
zigzag = wn.synset('zigzag.n.01').definition()
print(zigzag)
 
## Fix Strange synsets ##
strange = ["cake", "dolphin", "octopus", "raccoon", "rake", "saw", "scorpion", "table", "toaster", "van", "whale"]

def fix_synset(a_list):
    synset_list = []
    for word in a_list:
        a = wn.synsets(word)
        synset_list.append(a)
    return synset_list
w = fix_synset(strange)
print(w)
x = wn_syns(w)
y = lower(x)
z = clean(y)

## Fix strange definitions ##
print(z)
cake1 = wn.synset('patty.n.01').definition()
print(cake1)
cake2 = wn.synset('cake.n.03').definition()
print(cake2)
dolphin1 = wn.synset('dolphin.n.02').definition()
print(dolphin1)
octopus1 = wn.synset('octopus.n.02').definition()
print(octopus1)
raccoon1 = wn.synset('raccoon.n.02').definition()
print(raccoon1)
rake1 = wn.synset('pitch.n.05').definition()
print(rake1)
rake2 = wn.synset('rake.n.03').definition()
print(rake2)
saw1 = wn.synset('saw.n.02'). definition()
print(saw1)
saw2 = wn.synset('power_saw.n.01'). definition()
print(saw2)
scorpion1 = wn.synset('scorpio.n.03').definition()
print(scorpion1)
scorpion2 = wn.synset('scorpion.n.03').definition()
print(scorpion2)
table1 = wn.synset('table.n.02').definition()
print(table1)
table2 = wn.synset('table.n.03').definition()
print(table2)
table3 = wn.synset('mesa.n.01').definition()
print(table3)
table4 = wn.synset('table.n.05').definition()
print(table4)
table5 = wn.synset('board.n.04').definition()
print(table5)
toaster1 = wn.synset('toaster.n.02').definition()
print(toaster1)
van1 = wn.synset('vanguard.n.01').definition()
print(van1)
van2 = wn.synset('van.n.03').definition()
print(van2)
van3 = wn.synset('van.n.04').definition()
print(van3)
van4 = wn.synset('van.n.05').definition()
print(van4)
whale1 = wn.synset('whale.n.02').definition()
print(whale1)

# Most appropriate definition was selected, and synset assigned to object